###########################################################
# Paths

# Path where ETL creates raw dumps of dataset tables
dataset_dump_path: /var/lib/datacamp/dumps

# Keys
captcha_private_key: XXX
captcha_public_key: XXX

#sphinx
sphinx_server: localhost
sphinx_port: 9312

# google smtp
gmail_user: 'gmail_user'
gmail_password: 'gmail_password'
gmail_domain: 'gmail_domain'

google_analytics_code: 'XXX'

# canonical_url: 'datanest.fair-play.sk'
